apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: sarrawa363/backend:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: localhost #mysql-service
        - name: DB_USER
          value: sarrawa
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: passer #password
        - name: DB_NAME
          value: backend_db
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi" 
